GET http://localhost:3050/api/persons


###
DELETE  http://localhost:3050/api/persons/6130357433c820733

###
POST http://localhost:3050/api/persons 
content-type: application/json
                                                                  
{
    "name": "goodd okytraysd",
    "number":"08008767975778"  
}
