GET http://localhost:3050/api/persons



###
DELETE  http://localhost:3050/api/persons/612b86aee2b5af366a4b7b00

###
POST http://localhost:3050/api/persons 
content-type: application/json
                                                                  
{
    "name": "pityy",
    "number":"08008767"  
}